# Problem Set 2 - Econ 387
## Amir ElTabakh
## Due - 2/27/2022

1) Create the following as arrays and matrices:

In [1]:
# importing dependencies
import numpy as np

In [2]:
# 1a
a_array = np.array([1, 2, 3, 1])
print(a_array)

a_matrix = np.matrix([1, 2, 3, 1])
print(a_matrix)

[1 2 3 1]
[[1 2 3 1]]


In [3]:
# 1b
b_array = np.array([[1], [0], [1], [5]])
print(b_array)

b_matrix = np.matrix([[1], [0], [1], [5]])
print(b_matrix)

[[1]
 [0]
 [1]
 [5]]
[[1]
 [0]
 [1]
 [5]]


In [4]:
# 1c
A_array = np.array([[1, 3, 5], [2, 4, 6], [7, 9, 11]])
print(A_array)

A_matrix = np.matrix([[1, 3, 5], [2, 4, 6], [7, 9, 11]])
print(A_matrix)

[[ 1  3  5]
 [ 2  4  6]
 [ 7  9 11]]
[[ 1  3  5]
 [ 2  4  6]
 [ 7  9 11]]


In [5]:
# 1d
B_array = np.identity(3, dtype = int)
print(type(B_array))
print(B_array)

B_matrix = np.asmatrix(B_array)
print(type(B_matrix))
print(B_matrix)

<class 'numpy.ndarray'>
[[1 0 0]
 [0 1 0]
 [0 0 1]]
<class 'numpy.matrix'>
[[1 0 0]
 [0 1 0]
 [0 0 1]]


2) Create the following arrays:

In [6]:
# 2a
x = np.array([[1, 3], [2, 4]])
print(x)

[[1 3]
 [2 4]]


In [7]:
# 2b
y = np.identity(2, dtype = int)
print(y)

[[1 0]
 [0 1]]


In [8]:
# 2c
z = np.array([[x, x], [y, y]])
z

array([[[[1, 3],
         [2, 4]],

        [[1, 3],
         [2, 4]]],


       [[[1, 0],
         [0, 1]],

        [[1, 0],
         [0, 1]]]])

How would you extract x from z?

In [9]:
# 2d
x_from_z = z[0]
print(x_from_z)

[[[1 3]
  [2 4]]

 [[1 3]
  [2 4]]]


(3) Consider the arrays/matrices in (1). Calculate $a × a'$, $b + a'$, $A × A'$, $A^3$ and $A × B$ (where the multiplication follows the algebra of matrices). Note that a' is the transpose of $a$ and $A'$ is the transpose of A.

In [10]:
# a x a'
a_array @ np.transpose(a_array)

15

In [11]:
# b + a'
print(b_array + np.transpose(a_array))

[[2 3 4 2]
 [1 2 3 1]
 [2 3 4 2]
 [6 7 8 6]]


In [12]:
# A x A'
A_array @ np.transpose(A_array)

array([[ 35,  44,  89],
       [ 44,  56, 116],
       [ 89, 116, 251]])

In [13]:
# A^3
print(np.linalg.matrix_power(A_array, 3))

[[ 708 1068 1428]
 [ 904 1360 1816]
 [1884 2820 3756]]


In [14]:
# A x B
print(A_array @ B_array)

[[ 1  3  5]
 [ 2  4  6]
 [ 7  9 11]]


(4) Generate a 10 × 5 and a 5 × 10 array of matrices by randomly drawing observations from the standard normal distribution. Denote them A and B, respectively. Calculate C = A × B and replace diagonal elements of C to ones.

In [15]:
A = np.random.normal(0, 1, size=(10, 5))
B = np.random.normal(0, 1, size=(5, 10))
C = A @ B

rows, columns = C.shape

for i in range(rows):
    C[i, i] = 1
    
C

array([[ 1.        ,  1.26511953,  0.63058697,  0.06091366, -2.36266684,
         0.57399757,  1.30510813, -1.23294889,  1.71943212, -0.17987913],
       [ 0.1843481 ,  1.        , -0.62579669,  0.33765449,  2.19599706,
        -2.31319218, -1.7620322 ,  1.13006074, -0.45271122, -0.05816551],
       [ 1.76303216,  0.04644544,  1.        ,  2.91795261,  2.89855743,
        -2.73191987,  0.25314915,  2.75187656,  2.4878592 ,  0.91172223],
       [-0.81542772,  0.11844648,  1.54903806,  1.        , -3.37945736,
        -1.58580082,  1.26926685, -0.19537864,  4.55986503,  1.75997465],
       [ 1.99300924,  0.89038646,  0.56915251,  0.50314575,  1.        ,
         2.10350498,  1.41395627,  2.74456083,  2.49746321,  1.68261843],
       [ 0.2929365 ,  1.51596994, -0.06079493,  3.06962526,  1.85150139,
         1.        ,  1.31408534, -2.06473101,  0.01889914, -1.0117551 ],
       [ 1.76164246, -0.42524457,  0.5895135 ,  1.4883324 ,  0.338188  ,
        -2.86577895,  1.        , -0.27292453

(5) Generate a 20 × 15 array D using A in (4), and a 15 × 20 array E using B in (4).
Calculate F = D × E. Replace nonpositive (≤ 0) elements of F to 0.5

In [16]:
D = np.hstack((np.hstack((np.vstack((A, A)), np.vstack((A, A)))), np.vstack((A, A))))
print(D.shape)

(20, 15)


In [17]:
E = np.vstack((np.hstack((np.vstack((B, B)), np.vstack((B, B)))), np.hstack((B, B))))
print(E.shape)

(15, 20)


In [18]:
F = D @ E

for i in range(len(F)):
    for j in range(len(F[i])):
        if F[i, j] <= 0:
            F[i, j] = 0.5

F[:5, :5]

array([[0.5       , 3.79535858, 1.89176091, 0.18274099, 0.5       ],
       [0.55304431, 0.5       , 0.5       , 1.01296348, 6.58799119],
       [5.28909648, 0.13933633, 0.5       , 8.75385782, 8.6956723 ],
       [0.5       , 0.35533943, 4.64711419, 1.62045687, 0.5       ],
       [5.97902773, 2.67115937, 1.70745753, 1.50943725, 0.5       ]])

(6) Reshape D and E in (5) as 3 × 10 × 10 arrays.

In [19]:
D_reshape = D.reshape((3, 10, 10))
print(D_reshape.shape)
print(D_reshape)

(3, 10, 10)
[[[-5.84962108e-01  8.02191460e-02 -1.00004638e+00 -6.42782282e-02
    8.72734232e-01 -5.84962108e-01  8.02191460e-02 -1.00004638e+00
   -6.42782282e-02  8.72734232e-01]
  [-5.84962108e-01  8.02191460e-02 -1.00004638e+00 -6.42782282e-02
    8.72734232e-01  9.95215438e-02  1.71777320e-01  1.50158338e+00
   -5.61885346e-01 -3.02496657e-01]
  [ 9.95215438e-02  1.71777320e-01  1.50158338e+00 -5.61885346e-01
   -3.02496657e-01  9.95215438e-02  1.71777320e-01  1.50158338e+00
   -5.61885346e-01 -3.02496657e-01]
  [-4.22435181e-01  4.39422722e-01  1.77597083e+00  1.14792374e+00
   -3.54327936e-01 -4.22435181e-01  4.39422722e-01  1.77597083e+00
    1.14792374e+00 -3.54327936e-01]
  [-4.22435181e-01  4.39422722e-01  1.77597083e+00  1.14792374e+00
   -3.54327936e-01 -1.74981137e+00  9.05665642e-01 -9.58659501e-01
    1.02718085e-01  2.80895659e-01]
  [-1.74981137e+00  9.05665642e-01 -9.58659501e-01  1.02718085e-01
    2.80895659e-01 -1.74981137e+00  9.05665642e-01 -9.58659501e-01
    

In [20]:
E_reshape = E.reshape((3, 10, 10))
print(E_reshape.shape)
print(E_reshape)

(3, 10, 10)
[[[ 0.05136806 -0.26441786 -0.47442168 -1.55880525  0.0930988
    2.44486    -0.64956927  0.55972279 -1.80772406 -0.36243421]
  [ 0.05136806 -0.26441786 -0.47442168 -1.55880525  0.0930988
    2.44486    -0.64956927  0.55972279 -1.80772406 -0.36243421]
  [-0.18868802 -1.15689665  0.38423056 -1.59569479 -1.64439904
    1.1475479  -0.69572372  1.65701274  1.36223043  1.23171719]
  [-0.18868802 -1.15689665  0.38423056 -1.59569479 -1.64439904
    1.1475479  -0.69572372  1.65701274  1.36223043  1.23171719]
  [ 0.04022618 -0.27145542 -0.39361978  1.01971846  1.6918239
   -1.5168632  -0.47227169  0.74247051  0.20754148 -0.21104629]
  [ 0.04022618 -0.27145542 -0.39361978  1.01971846  1.6918239
   -1.5168632  -0.47227169  0.74247051  0.20754148 -0.21104629]
  [ 0.8964387   1.16195369  0.13399624  1.13223357  0.40931422
    0.58026314  1.18531388  0.73222753  0.94996155  0.2739058 ]
  [ 0.8964387   1.16195369  0.13399624  1.13223357  0.40931422
    0.58026314  1.18531388  0.73222753  

(7) Set `x = np.arange(100.0)`. Use shape attribute to reshape x into 10 × 10, 20 × 5,
10 × 10 × 1 arrays.

In [21]:
x = np.arange(100.0)

# 7a
x_a = x.reshape((10, 10))
print(x_a.shape)

# 7b
x_b = x.reshape((20, 5))
print(x_b.shape)

# 7c
x_c = x.reshape((10, 10, 1))
print(x_c.shape)

(10, 10)
(20, 5)
(10, 10, 1)


(8) Set `x = np.reshape(np.arange(100.0),(5,20))`. Use `ravel`, `flatten` and `flat` to
extract elements {1, 3, . . . , 99} from x.

In [22]:
x = np.reshape(np.arange(100.0),(5,20))

# 8a
print(x.ravel()[1:])

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53. 54.
 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71. 72.
 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89. 90.
 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [23]:
# 8b
print(x.flatten()[1:])

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53. 54.
 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71. 72.
 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89. 90.
 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [24]:
# 8c
print(x.flat[1:])

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53. 54.
 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71. 72.
 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89. 90.
 91. 92. 93. 94. 95. 96. 97. 98. 99.]


(9) Generate the provided matrices and use `hstack`, `vstack` and `tile` to generate m. Find the shape and
dimension of m. Extract z' from m.

In [25]:
# generating matrices
x = np.matrix([[16, 10], [13, 11]])
y = np.matrix([5])
z = np.matrix([[16, 10], [13, 11],[12, 33]])

m_top_half = np.hstack((x, np.vstack((np.hstack((np.hstack((y, y)), y)), np.hstack((np.hstack((y, y)), y))))))
print(m_top_half)

m_lower_half = np.hstack((z, np.vstack((np.transpose(z), np.hstack((y, np.hstack((y, y))))))))
print(m_lower_half)

[[16 10  5  5  5]
 [13 11  5  5  5]]
[[16 10 16 13 12]
 [13 11 10 11 33]
 [12 33  5  5  5]]


In [26]:
# all together
m = np.matrix(np.vstack((m_top_half, m_lower_half)))
print(m.shape)
print(m)

(5, 5)
[[16 10  5  5  5]
 [13 11  5  5  5]
 [16 10 16 13 12]
 [13 11 10 11 33]
 [12 33  5  5  5]]


In [27]:
# Extract z' from m.
import pandas as pd
m_df = pd.DataFrame(m)

print(np.transpose(z))
z_transpose_from_m = m_df.iloc[2:4, 2:]
z_transpose_from_m

[[16 13 12]
 [10 11 33]]


2   3   4
2  16  13  12
3  10  11  33

(10) Using the diagonal elements of m in (9) construct a diagonal array. Also, compute
eigenvalues, rank, determinant, inverse, trace of m in (9).


In [28]:
# diagonal
print(f"Diagonal: {np.diag(m)}\n")

# eigenvalues
print(f"Eigenvalues: {np.linalg.eig(m)[0]}\n")

# rank
print(f"Rank: {np.linalg.matrix_rank(m)}\n")

# determinant
print(f"Determinant: {round(np.linalg.det(m), 5)}\n")

# inverse
print(f"Inverse: {np.linalg.inv(m)}\n")

# trace
print(f"Trace: {np.trace(m)}")

Diagonal: [16 11 16 11  5]

Eigenvalues: [52.35863225+0.j         -0.20748019+5.87006351j -0.20748019-5.87006351j
  2.66013743+0.j          4.3961907 +0.j        ]

Rank: 5

Determinant: 21125.0

Inverse: [[ 3.38461538e-01 -3.53846154e-01  1.56465255e-17 -1.76023412e-18
   1.53846154e-02]
 [ 1.53846154e-02 -6.15384615e-02  2.72113486e-18 -3.06127672e-19
   4.61538462e-02]
 [ 2.22030769e+00 -3.53046154e+00  3.38461538e-01  1.53846154e-02
   3.96307692e-01]
 [-3.48430769e+00  5.33415385e+00 -3.53846154e-01 -6.15384615e-02
  -5.94461538e-01]
 [ 3.50153846e-01 -5.48307692e-01  1.53846154e-02  4.61538462e-02
   5.66153846e-02]]

Trace: 59
